workflows:
  version: 2
  build-deploy:
    jobs:
      - build

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      # build the application image
      - run:
          name: Docker Builds
          command: |
            echo "Building quued version of all images in images.txt"
            cat .circleci/images.txt
            bash .circleci/buildConvienceImages.sh
