workflows:
  version: 2
  build-deploy:
    jobs:
      - testing
      - build:
          requires: 
            - testing
          filters:
            branches:
              only: master


version: 2
jobs:
  testing:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - run:
          name: Queue Build
          command: |
            # wait up to 1 minute for previous builds
            python src/queueBuildUntilFrontOfLine.py 1

      - run:
          name: Do Slow Things
          command: |
            # This step mimics a slow deployment or other activity to wait for, single concurrency
            sleep 30 #30 seconds is less than max wait above, so only if we queue many jobs will they start to abort

  build:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - run:
          name: Test
          command: |
            echo "TODO"
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t eddiewebb/circleci-queue:build-$CIRCLE_BUILD_NUM -t eddiewebb/circleci-queue:latest .

      # deploy the image
      - run: docker push eddiewebb/circleci-queue:build-$CIRCLE_BUILD_NUM  
